### ISSUE TITLE
Design how to select colours after color thief chose them based on logo

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/wap-huenique-theme#1]
Conditions:
- what if logo has very simple (eg black and white) colours -> if colors already exist in global colors don't choose them and just alert the user
- what if logo has primary colour with low contrast (darkish) -> choose complementary colours to the colour
- how about pick one colour from logo (primary) and chose complementary colours
- don't use any of the colours -> generate an error because there is no good enough colours to use or file is invalid

**Comment by asirota** [comment]
Here are some logos to play with...
![logo](https://user-images.githubusercontent.com/458134/188952226-38ee8ec4-11b0-4a83-a1d7-176aa876f625.svg)
![SNCC-362c-2756c](https://user-images.githubusercontent.com/458134/188952228-2e58a526-1b02-4d74-89c2-97993e2e80f3.png)
![archivists-logo](https://user-images.githubusercontent.com/458134/188952229-89f022fd-d547-4873-a744-cd8fa7cf7493.png)

**Comment by natbrotherton** [comment]
Resolved by #8
